### ISSUE TITLE
Implementar Linting

### ISSUE THREAD

**Issue by david81brs** [training-center/hades#23]
# Linting
Conforme Ata [26-11-2017](https://github.com/david81brs/plataforma/blob/master/meetings/minutes/doc/20171126.md) implementar no Hades ferramenta de verificação de estilo e código (lint). Em pesquisa verifica-se que uma das ferramentas possíveis é o [eslint](https://eslint.org/). Contudo, é preciso definir o estilo que será aplicado para a formação do código. 
O eslint oferece alguns estilos:
- Google
- Airbnb
- Personalização

Já temos uma ideia de que estilo será seguido? No _Front-end_ o eslint está sendo utilizado.

**Comment by vcapretz** [comment]
@david81brs posso enviar uma sugestão de implementação usando o [xo](https://github.com/sindresorhus/xo), ele é baseado no eslint, mas vem com bastante configuração padrão que já observei ser bastante comum em outros projetos, no futuro podemos adicionar/remover/alterar configurações de acordo com o nosso caso.

qualquer coisa podemos discutir mais da ideia na PR q vou abrir!
